# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='booked',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=30)),
        #         ('date', models.DateField()),
        #         ('stime', models.TimeField()),
        #         ('etime', models.TimeField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='check_rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.SmallIntegerField()),
                ('capacity', models.SmallIntegerField()),
                ('date', models.DateField()),
                ('stime', models.TimeField(default='01:00', null=True)),
                ('etime', models.TimeField(default='01:00', null=True)),
                ('proom', models.CharField(max_length=120)),
                ('floor', models.SmallIntegerField()),
                ('mike', models.SmallIntegerField()),
                ('stage', models.SmallIntegerField()),
                ('projector', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='incharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.SmallIntegerField()),
                ('department', models.CharField(max_length=50)),
                ('incharge', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('incharge', models.CharField(max_length=120)),
                ('desig', models.CharField(max_length=120)),
                ('avail', models.SmallIntegerField(default='1')),
                ('depart', models.CharField(default=' ', max_length=50)),
                ('capacity', models.SmallIntegerField()),
                ('floor', models.SmallIntegerField()),
                ('mike', models.SmallIntegerField(default='0')),
                ('stage', models.SmallIntegerField(default='0')),
                ('projector', models.SmallIntegerField(default='0')),
                ('msp', models.SmallIntegerField()),
                ('wpoints', models.SmallIntegerField(default='0')),
            ],
        ),
    ]
