# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0002_booked_check_rooms2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_rooms',
            name='etime',
        ),
        migrations.RemoveField(
            model_name='check_rooms',
            name='stime',
        ),
    ]
