# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0003_auto_20160926_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='wpoints',
        ),
    ]
