# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0006_auto_20160928_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
