# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0007_rooms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='image',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
