# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0009_auto_20160929_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_rooms',
            name='mike',
        ),
        migrations.RemoveField(
            model_name='check_rooms',
            name='projector',
        ),
        migrations.RemoveField(
            model_name='check_rooms',
            name='stage',
        ),
    ]
