# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0010_auto_20160929_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_rooms',
            name='etime',
            field=models.CharField(default='01:00', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='check_rooms',
            name='stime',
            field=models.CharField(default='01:00', max_length=5, null=True),
        ),
    ]
