# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0011_auto_20160929_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='etime',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='booked',
            name='stime',
            field=models.CharField(max_length=5),
        ),
    ]
