# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0012_auto_20160929_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_rooms',
            name='date',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
