# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0013_auto_20160930_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='date',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
