# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0014_auto_20160930_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='incharge',
            name='profid',
            field=models.SmallIntegerField(null=True),
        ),
    ]
