# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_room', '0015_incharge_profid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='reqid',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='userid',
            field=models.SmallIntegerField(null=True),
        ),
    ]
