# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default='2016-01-01'),
        ),
    ]
