# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default='2016-01-01'),
        ),
    ]
