# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='userid',
            field=models.SmallIntegerField(null=True),
        ),
    ]
