# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_dev_prof_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof_contact',
            name='image',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
