# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_prof_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.FileField(null=True, upload_to=b'')),
            ],
        ),
    ]
