# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.SmallIntegerField()),
                ('reqid', models.SmallIntegerField(default='10')),
                ('eventname', models.CharField(max_length=120)),
                ('eventroom', models.CharField(max_length=120)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('status', models.SmallIntegerField()),
                ('condby', models.CharField(max_length=25)),
                ('condbyname', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.SmallIntegerField(default='0')),
                ('reqid', models.SmallIntegerField(default='0')),
                ('message', models.CharField(default=' ', max_length=200)),
                ('step1', models.SmallIntegerField(default=0)),
                ('step2', models.SmallIntegerField(default=-2)),
                ('step3', models.SmallIntegerField(default=-2)),
                ('step4', models.SmallIntegerField(default=-2)),
            ],
        ),
    ]
