# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_detail',
            name='bdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
