# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_detail', '0003_auto_20160928_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
