# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_detail', '0004_auto_20160930_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_detail',
            name='etime',
            field=models.TimeField(null=True),
        ),
    ]
