# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_detail', '0005_book_detail_etime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
